version: 0.2

phases:
 install:
   runtime-versions:
        nodejs: 10
   commands:
     - echo "install step"
 pre_build:
   commands:
     - echo "pre_build step"
 build:
   commands:
     - aws s3 sync --delete . "arn:aws:s3:::www.nuxt-aws-app.com"
 post_build:
   commands:
     - echo "post_build step"